services:
  service-analyzer:
    image: service-analyzer:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    container_name: service-analyzer

    ports:
      - "9002:9002"

    environment:
      SPRING_PROFILES_ACTIVE: dev

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.8.2:5432/contract_lens_anz
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # RabbitMQ
      SPRING_RABBITMQ_HOST: 192.168.8.2
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: contractlens_user
      SPRING_RABBITMQ_PASSWORD: contractlens_pass

      # MongoDB
      SPRING_DATA_MONGODB_HOST: 192.168.8.2
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: contractlens
      SPRING_DATA_MONGODB_USERNAME: contractlens
      SPRING_DATA_MONGODB_PASSWORD: contractlens123
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: admin


      # Redis
      SPRING_DATA_REDIS_HOST: 192.168.8.2
      SPRING_DATA_REDIS_PORT: 7000
      SPRING_DATA_REDIS_PASSWORD: ""
      SPRING_DATA_REDIS_TIMEOUT: 5000ms
      SPRING_DATA_REDIS_DATABASE: 0

    restart: unless-stopped

    networks:
      - contractlens-network


networks:
  contractlens-network:
    external: true